apiVersion: v1
kind: Pod
spec:
  containers:
  - name: 'maven'
    image: "maven:3.6.2-jdk-8-slim"
    tty: true
    command:
    - cat
    volumeMounts:
    - name: maven-repo
      mountPath: /root/.m2/repository
  volumes:
  - name: maven-repo
    persistentVolumeClaim:
      claimName: maven-repo
