apiVersion: v1
kind: Pod
spec:
  containers:
  - name: 'jnlp'
    securityContext:
      runAsUser: 1000
    image: "maven:3.6.2-jdk-8-slim"
    tty: true
    command:
    - sh
    args: 
    - /var/jenkins_config/jenkins-agent
    volumeMounts:
    - mountPath: /var/jenkins_config
      name: jenkins-agent
  - name: 'nodejs'
    image: "node:13-buster"
    tty: true
    command:
    - cat
  volumes:
  - name: jenkins-agent
    configMap:
      name: jenkins-agent
      path: /var/jenkins_config
